ACT/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Recruitment_System.urls')),
    path('company/', include('Company.urls')),
    path('user-admin/', include('UserAdmin.urls')),
    path('froala_editor/', include('froala_editor.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Recruitment_System/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.registration_view, name="signup"),
    path('job-list/', views.job_list, name='job-list'),
    path('job-sector/<slug:slug>', views.job_sector_categories, name='job_sector_categories'),
    path('job-detail/<slug:slug>', views.job_detail, name='Job-detail'),
    #User
    path('user-add-bookmark/<slug:slug>', views.user_add_bookmark, name="user-add-bookmark"),
    path('user-remove-bookmark/<slug:slug>', views.user_delete_bookmark, name='user-delete-bookmark'),
    path('user-apply-job/<slug:slug>', views.user_apply_job, name='user-apply-job'),
    path('user-cancel-job/<slug:slug>', views.user_cancel_job, name='user-cancel-job'),
    path('resetpassword/', views.reset_password, name='reset-password'),
    path('login/', views.login, name='login'),
    path('user-dashboard/', views.user_dashboard, name='user-dashboard'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('user-add-resume/', views.user_resume, name='user-resume'),
    path('user-add-education/', views.user_add_education, name='user-add-education'),
    path('user-education/<slug:slug>/',views.detail_user_education, name='detail-user-education'),
    path('user-delete-education/<slug:slug>',views.user_delete_education, name='user-delete-education'),
    path('user-add-experience/', views.user_add_experience, name='user-add-experience'),
    path('user-experience/<slug:slug>/',views.detail_user_experience, name='detail-user-experience'),
    path('user-delete-experience/<slug:slug>',views.user_delete_experience, name='user-delete-experience'),
    path('user-applied-job/', views.user_applied_jobs, name='user-applied-job'),
    path('user-bookmark/', views.user_bookmark, name='user-bookmark'),
    path('user-change-password/', views.user_change_password, name='user-change-password'),
    #Interviewer
    path('interviewer-dashboard/', views.interviewer_dashboard, name='interviewer-dashboard'),
    path('interviewer-info/', views.interviewer_personal_info, name='interviewer-personal-info'),
    path('interviewer-job-list/', views.interviewer_job_list, name='interviewer-job-list'),
    path('interviewer-job-detail/<slug:slug>', views.interviewer_job_detail, name='interviewer-job-detail'),
    path('interviewer-interviews-list/', views.interviewer_interviews_lists, name='interviewer-interviews-list'),
    path('interview-detail/<slug:slug>', views.interview_detail, name='interview_detail'),
    path('cancel-interview/<slug:slug>', views.interview_cancel, name='cancel-interview'),
    path('interview-scheduled/', views.interview_scheduled, name='interview-scheduled'),
    path('today-interviews/', views.interview_today_interview_list, name='today-interviews'),
    path('interview-now/<slug:slug>', views.interview_individual_now, name="interviews-now"),
    path('interview-job-status/', views.interview_candidate_job_status, name="interview-job-status"),
    path('interview-applicant-category/<slug:slug>', views.interview_applicant_category, name='interview_applicant_category')
]

Recruitment_System/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from froala_editor.fields import FroalaField
from Account.models import CustomUser
from django.utils.text import slugify
from unidecode import unidecode
import datetime
#Candidate
gender_list = [
    ('male', 'Male'),
    ('female', 'Female'),
]

class Candidate(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=10, choices=gender_list)
    date_of_birth = models.DateField()
    email = models.EmailField(max_length=40)
    phone1 = PhoneNumberField()
    phone2 = PhoneNumberField(blank = True)
    address = models.CharField(max_length=100)
    linked_in = models.URLField(blank=True, null=True)
    git_hub = models.URLField(blank=True, null=True)
    country = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    photo = models.ImageField(upload_to='Candidate/photo', null=True, blank=True)
    resume = models.FileField(upload_to='Candidate/Resume', null=True, blank=True)
    about = models.TextField()
    skill = models.ManyToManyField("Skill", blank=False) 
    slug = models.SlugField(unique=True, blank=True,  max_length=200)
    date_created = models.DateField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name
    
    def age(self):
        date = datetime.datetime.now()
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.user.username))
        super().save(*args, **kwargs)

education_status_list = [
    ('highschool', 'High School'),
    ('Certificate', 'Certificate'),
    ('diploma', 'Diploma'),
    ('bachelor-degree', "Bachelor's degree"),
    ('Master-degree', "Master's Degree"),
    ('doctorate', "Doctorate"),
    ('other', 'Other')
]

class Education(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    institution_name = models.CharField(max_length=100)
    education_status = models.CharField(max_length=40, choices=education_status_list)
    field_of_study = models.CharField(max_length=40)
    education_period_start = models.DateField()
    education_period_end = models.DateField()
    slug = models.SlugField(unique=True, blank=True, max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) + "-" + slugify(unidecode(self.institution_name)) + "-" + slugify(unidecode(self.field_of_study))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.institution_name

class Experience(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    company_name = models.CharField(max_length=40)
    work_time_line_start =models.DateField()
    work_time_line_end = models.DateField()
    job_title = models.CharField(max_length=50)
    reference_phone = PhoneNumberField()
    reference_name = models.CharField(max_length=40)
    reference_email = models.CharField(max_length=40)
    reference_job_title = models.CharField(max_length=40)
    responsibility = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) +"-"+slugify(unidecode(self.company_name))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.company_name

class Skill(models.Model):
    title = models.CharField(unique=True, max_length=30)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['title']
   
    def __str__(self) -> str:
        return self.title
    
class Bookmarks(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job = models.ForeignKey('Job_Posting', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True,blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.user.username)) + "-" + slugify(unidecode(self.job.title))+ '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.job.title


class Sector(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)

    def count_job_post(self) -> int:
        count = Job_Posting.objects.filter(sector_id = self.id).count()
        return count
    
    def count_interview_completed(self) -> int:
        applicant = Interviews.objects.filter(status='completed', application__job__sector_id = self.id).count()
        return applicant


    def __str__(self) -> str:
        return self.name


job_type = [
    ('full_time', 'Full Time'),
    ('part_time', 'Part Time'),
    ('freelance', 'Freelance'),
    ('internship', 'Internship'),
    ('seasonal ','seasonal'),
    ('contract', 'Contract'),
    ('remote', 'Remote'),
]


class Job_Posting(models.Model):
    title = models.CharField(max_length=50)
    sector = models.ForeignKey(Sector, on_delete=models.SET_NULL, null=True)  # Related With Sector
    description = FroalaField()
    vacancies = models.IntegerField()
    experience = models.CharField(max_length=20)
    skills = models.ManyToManyField(Skill)
    location = models.CharField(max_length=200)
    salary_range_start = models.FloatField()
    salary_range_final = models.FloatField()
    type = models.CharField( choices=job_type, max_length=30)
    job_status = models.BooleanField(default=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_closed = models.DateField()
    slug = models.SlugField(unique=True,  max_length=200, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
  
    class Meta:
        ordering = ['-date_posted','-date_closed']

    def count_applicant(self) -> int:
        applicant = Application.objects.filter(job__id = self.id).count()
        return applicant
    
    def count_interview_pending(self) -> int:
        applicant = Application.objects.filter(status='pending', job__id = self.id).count()
        return applicant
    
    def count_interview_completed(self) -> int:
        applicant = Interviews.objects.filter(status='completed', application__job__id = self.id).count()
        return applicant

    def __str__(self) -> str:
        return self.title

application_status = [
    ('pending', 'Pending'),
    ('in_review', 'In review'),
    ('rejected', 'Rejected'),
    ('hired', 'Hired')
]

class Application(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)  # Related with Candidate
    job = models.ForeignKey(Job_Posting, on_delete=models.SET_NULL, null=True)  # Related with Job_Post
    date_applied = models.DateField(auto_now_add=True) # Select Option from application_status
    status = models.CharField(max_length=15, choices=application_status, default='pending')
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.user.username)) + '-' + slugify(unidecode(self.job.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return str(self.user.username)+" - "+str(self.job)
    
    class Meta:
       ordering = ['-date_applied']

interview_status = [
    ('pending', 'Pending'),
    ('scheduled', 'Scheduled'),
    ('completed', 'Completed'),
    ('canceled', 'Canceled'),
]

job_status_interview = [
    ('pending', 'Pending'),
    ('rejected', 'Rejected'),
    ('hired', 'hired'),
]

interview_type = [
    ('phone', 'Phone'),
    ('in-person', 'In-Person'),
    ('video', 'Video')
]

class Interviews(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True, blank=True)
    interviewer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)  # Related with User
    date_schedule = models.DateField(null=True, blank=True)
    time_schedule = models.TimeField(null=True, blank=True)
    status = models.CharField(max_length=15, choices=interview_status, default='pending', null=True, blank=True)
    type = models.CharField(max_length=15, choices=interview_type, null=True, blank=True)
    note = FroalaField( null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=600)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()

Recruitment_System/templates/RMS/user/dashboard-applied-jobs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Themezhub" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bookmarks | ACT - American College Of Technology </title>
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css" />
    {% include 'include/head.html' %}
  </head>

  <body>
		<div class="mt-5">{% include 'include/navbar.html'%}</div>
    <div id="main-wrapper">
      <div class="dashboard-wrap bg-light">
		 <!--Left Navbar-->
		{% include 'RMS/user/include/user-dashboard.html'%}
        <div class="dashboard-content">
          <div class="dashboard-tlbar d-block mb-5">
            <div class="row">
              <div class="colxl-12 col-lg-12 col-md-12">
                <h1 class="ft-medium">Applied Jobs</h1>
              </div>
            </div>

                      <!--Messages-->
          <div class="row d-flex  justify-content-center">
            <div class="col-8">
              
               {% if messages %}
               <ul class="messages">
                   {% for message in messages %}
                   <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}  alert-dismissible">
                     <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                      {{message}}
                   </div>
                   {% endfor %}
               </ul>
               {% endif %}
            </div>
          </div>
          <!--End Message-->
          
          </div>

          <div class="dashboard-widg-bar d-block mb-5">
            <div class="row">
              <div class="col-xl-12 col-md-12 col-sm-12">
                <div class="cl-justify">
                  <div class="cl-justify-first">
                    <p class="m-0 p-0 ft-sm">
                      You have {{application.filter.all.count}} jobs bookmarked.
                    </p>
                  </div>

                  <div class="cl-justify-last">
                    <div class="d-flex align-items-center justify-content-left">
                      <div class="dlc-list">
                        <select class="form-control sm rounded">
                          <option>All Jobs</option>
                          <option>Full Time</option>
                          <option>Part Time</option>
                          <option>Freelancing</option>
                          <option>Internship</option>
                          <option>Contract</option>
                        </select>
                      </div>
                      <div class="dlc-list ms-2">
                        <select class="form-control sm rounded">
                          <option>Show 20</option>
                          <option>Show 30</option>
                          <option>Show 40</option>
                          <option>Show 50</option>
                          <option>Show 100</option>
                          <option>Show 250</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="mb-4 tbl-lg rounded overflow-hidden">
                  <div class="table-responsive bg-white">
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Job Title</th>
                          <th scope="col">Vacancies</th>
                          <th scope="col">Close Date</th>
                          <th scope="col">Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <table id="example" class="display " style="width:100%">
                          <thead>
                              <tr>
                                  <th>Job Title</th>
                                  <th>Vacancies</th>
                                  <th>Applied Date</th>
                                  <th>Application Status</th>
                                  <th>Interview Status</th>
                                  <th>Action</th>
                              </tr>
                          </thead>
                          <tbody class="bg-white">
                            {% for app in application %}
                            <tr class="bg-white">
                              <td class="bg-white">
                                <div class="cats-box rounded d-flex align-items-center">
                                  <div class="text-center">
                                    
                                  </div>
                                  <div class="cats-box-caption px-2">
                                    <h4 class="fs-md mb-0 ft-medium">
                                      {{app.job.title}}
                                    </h4>
                                    <div class="d-block mb-2 position-relative">
                                      <span class="muted medium ms-2 theme-cl"><i class="lni lni-briefcase me-1"></i>{{app.job.get_type_display}}</span>
                                    </div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <span>{{ app.job.vacancies}}</span>
                              </td>
                              <td>
                                <span>{{ app.date_applied }}</span>
                              </td>
                              <td><span class="text-info">{{app.get_status_display}}</span></td>
                              <td><span class="text-dark fw-bold">
                                {% for interview in interviews %}
                                    {% if app.id is interview.application.id %}
                                           {% if interview.status %}
                                               {{ interview.get_status_display}}
                                           {% endif %}
                                    {% endif %}
                                {% endfor %}
                              </span></td>
                              <td>
                                <div class="dash-action">
                                  <a
                                    href="{% url 'Job-detail' app.job.slug %}"
                                    class="p-2 circle text-info bg-light-info d-inline-flex align-items-center justify-content-center me-1"
                                    ><i class="lni lni-eye"></i
                                  ></a>
                                  <a href="{% url 'user-cancel-job' app.job.slug%}"
                                    class="btn p-2 circle  btn-danger d-inline-flex align-items-center justify-content-center ms-1"
                                    ><i class="lni lni-trash-can"></i
                                  ></a>
                                </div>
                              </td>
                              
                            </tr>
                            {% endfor %}
                             
                          </tbody>
                      </table>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
      <!-- ======================= dashboard Detail End ======================== -->

      <a id="back2Top" class="top-scroll" title="Back to top" href="#"
        ><i class="ti-arrow-up"></i
      ></a>
    </div>
    {% include 'include/footer.html' %} 
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script>
      new DataTable('#example');
    </script>
    {% include 'include/footerjs.html' %} 
  </body>
</html>

Recruitment_System/templates/RMS/user/dashboard-saved-jobs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Themezhub" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bookmarks | ACT - American College Of Technology </title>
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css" />
    {% include 'include/head.html' %}
  </head>

  <body>
		<div class="mt-5">{% include 'include/navbar.html'%}</div>
    <div id="main-wrapper">
      <div class="dashboard-wrap bg-light">
		 <!--Left Navbar-->
		{% include 'RMS/user/include/user-dashboard.html'%}
        <div class="dashboard-content">
          <div class="dashboard-tlbar d-block mb-5">
            <div class="row">
              <div class="colxl-12 col-lg-12 col-md-12">
                <h1 class="ft-medium">Saved Jobs</h1>
              </div>
            </div>

                      <!--Messages-->
          <div class="row d-flex  justify-content-center">
            <div class="col-8">
              
               {% if messages %}
               <ul class="messages">
                   {% for message in messages %}
                   <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}  alert-dismissible">
                     <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                      {{message}}
                   </div>
                   {% endfor %}
               </ul>
               {% endif %}
            </div>
          </div>
          <!--End Message-->
          
          </div>

          <div class="dashboard-widg-bar d-block mb-5">
            <div class="row">
              <div class="col-xl-12 col-md-12 col-sm-12">
                <div class="cl-justify">
                  <div class="cl-justify-first">
                    <p class="m-0 p-0 ft-sm">
                      You have {{bookmarks.filter.all.count}} jobs bookmarked.
                    </p>
                  </div>

                  <div class="cl-justify-last">
                    <div class="d-flex align-items-center justify-content-left">
                      <div class="dlc-list">
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="mb-4 tbl-lg rounded overflow-hidden">
                  <div class="table-responsive bg-white">
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Job Title</th>
                          <th scope="col">Vacancies</th>
                          <th scope="col">Close Date</th>
                          <th scope="col">Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <table id="example" class="display " style="width:100%">
                          <thead>
                              <tr>
                                  <th>Job Title</th>
                                  <th>Vacancies</th>
                                  <th>Close Date</th>
                                  <th>Status</th>
                                  <th>Action</th>
                              </tr>
                          </thead>
                          <tbody class="bg-white">
                            {% for book in bookmarks %}
                            <tr class="bg-white">
                              <td class="bg-white">
                                <div class="cats-box rounded d-flex align-items-center">
                                  <div class="text-center">
                                    
                                  </div>
                                  <div class="cats-box-caption px-2">
                                    <h4 class="fs-md mb-0 ft-medium">
                                      {{book.job.title}}
                                    </h4>
                                    <div class="d-block mb-2 position-relative">
                                      <span class="muted medium ms-2 theme-cl"><i class="lni lni-briefcase me-1"></i>{{book.job.get_type_display}}</span>
                                    </div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <span>{{ book.job.vacancies}}</span>
                              </td>
                              <td>
                                <span>{{ book.job.date_closed }}</span>
                              </td>
                              <td><span class="text-info">{%if book.job.job_status%}Active{% else%} Closed {% endif%}</span></td>

                              <td>
                                <div class="dash-action">
                                  <a
                                    href="{% url 'Job-detail' book.job.slug %}"
                                    class="p-2 circle text-info bg-light-info d-inline-flex align-items-center justify-content-center me-1"
                                    ><i class="lni lni-eye"></i
                                  ></a>
                                  <a href="{% url 'user-delete-bookmark' book.job.slug%}"
                                    class="btn p-2 circle  btn-danger d-inline-flex align-items-center justify-content-center ms-1"
                                    ><i class="lni lni-trash-can"></i
                                  ></a>
                                </div>
                              </td>
                              
                            </tr>
                            {% endfor %}
                             
                          </tbody>
                      </table>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
      <!-- ======================= dashboard Detail End ======================== -->

      <a id="back2Top" class="top-scroll" title="Back to top" href="#"
        ><i class="ti-arrow-up"></i
      ></a>
    </div>
    {% include 'include/footer.html' %} 
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script>
      new DataTable('#example');
    </script>
    {% include 'include/footerjs.html' %} 
  </body>
</html>