ACT/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Recruitment_System.urls')),
    path('company/', include('Company.urls')),
    path('user-admin/', include('UserAdmin.urls')),
    path('froala_editor/', include('froala_editor.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Company/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>',views.single_blog, name='single_blog'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('privacy-and-policy/', views.privacy_and_policy, name='Privacy-policy'),
    path('faqs/', views.faqs, name='faqs')
]

Company/models.py
from django.db import models
from django.utils.text import slugify
from froala_editor.fields import FroalaField
from unidecode import unidecode
import datetime
from phonenumber_field.modelfields import PhoneNumberField
from fontawesome_5.fields import IconField

# Create your models here.


#Blog 
class Blog_Categories(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True,blank=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.name)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
    
    def count_categories(self):
        return Blog.objects.filter(__type = self.name).count()
    
    def __str__(self) -> str:
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=200, blank=True)
    image = models.ImageField(upload_to='blog/')
    description = models.CharField(max_length=400)
    content = FroalaField()
    type = models.ManyToManyField(Blog_Categories)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at', '-updated_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
    
    def count_comment(self):
        return Comment.objects.filter(blog = self.id).count()
    
    def __str__(self) -> str:
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    comment = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self) -> str:
        return self.name

#Contact 
class Contact(models.Model):
    phone = PhoneNumberField()
    email = models.EmailField()
    location = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.email

class Social_Media(models.Model):
    name = models.CharField(max_length=30)
    icon = IconField()
    link = models.URLField()

    def __str__(self) -> str:
        return self.name


class Contact_Message(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self) -> str:
        return self.name

Company/forms.py
from django import forms
from  .models import Comment, Contact_Message

class CommentForm(forms.ModelForm):
    name = forms.CharField(max_length=40, error_messages={'required' : 'Can not be empty'})
    email = forms.EmailField(widget=forms.TextInput(), error_messages={'required' : 'Can not be empty'})
    comment = forms.CharField(widget=forms.TextInput(), error_messages={'required': 'Can not be empty'})
    
    class Meta:
        model = Comment
        fields = ['name', 'email', 'comment']

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 2:
            raise forms.ValidationError(' Enter a valid name.')
        return name

class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=40, error_messages={'required' : 'Can not be empty'})
    email = forms.EmailField(error_messages={'required' : 'Can not be empty'})
    subject = forms.CharField(error_messages={'required' : 'Can not be empty'})
    message = forms.CharField(widget=forms.TextInput, error_messages={'required' : 'Can not be empty'})

    class Meta:
        model = Contact_Message
        fields = '__all__'
    
    def clean_name(self):
     name = self.cleaned_data['name']
     if len(name) < 2:
         raise forms.ValidationError(' Enter a valid name.')
     return name

Company/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Blog, Comment, Social_Media, Contact
from .forms import CommentForm, ContactForm
from django.contrib import messages
# Create your views here.
social_medias = Social_Media.objects.all()

def blog(request):
    try:
        latest_blog = Blog.objects.first()
        blogs = Blog.objects.all().exclude(id = latest_blog.id)
    except:
        latest_blog  = None
        blogs = None
    
    paginator = Paginator(blogs, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'social_medias' : social_medias,
        'latest_blog' : latest_blog,
        'blogs' : page,
        
    }
    return render(request, 'Company/blog.html', context)

def single_blog(request, slug):
    blog = Blog.objects.filter(slug = slug).first()
    latest_post = Blog.objects.all().exclude(slug = slug)[:4]
    comments =  Comment.objects.filter(blog__pk = blog.pk)
   
    form = CommentForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.save()
            messages.success(request, 'Your comment has been successfully sent!')
            form = CommentForm()

    context = {
        'social_medias' : social_medias,
        'blog' : blog,
        'latest_posts' : latest_post,
        'form' : form,
        'comments' : comments
    }
    return render(request, 'Company/blog-details.html', context)

def contact(request):
    contact = Contact.objects.all().first()
    if request.method == 'POST':
        form = ContactForm(request.POST)  
        if form.is_valid():
            form.save()
            messages.success(request, 'Your request has been successfully sent')
            form = ContactForm()
    else:
        form = ContactForm()


    context = {
        'social_medias' : social_medias,
        'contact' : contact,
        'form' : form
    }
    return render(request, 'Company/contact.html', context)

def about(request):
    context = {
        'social_medias' : social_medias,
    }
    return render(request, 'Company/about.html',context)

def privacy_and_policy(request):
    context = {
        'social_medias' : social_medias,
    }
    return render(request, 'Company/privacy-policy.html', context)

def faqs(request):
    context = {
        'social_medias' : social_medias,
    }
    return render(request, 'Company/faqs.html',context)

Company/templates/Company/blog.html
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Blog | ACT - American College Of Technology </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content=" " />
  <meta name="keywords" content="" />
  <meta content="Themesdesign" name="author" />
  
 
  {% include 'include/head.html' %}

</head>

<body>


  <!-- Begin page -->
  <div>

    {% include 'include/navbar.html' %}
    <div class="main-content">
      <div class="page-content">
        <!-- Start home -->
        <section class="page-title-box">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <div class="text-center text-white">
                  <h3 class="mb-4">Blog</h3>
                  <div class="page-next">
                    <nav class="d-inline-block" aria-label="breadcrumb text-center">
                      <ol class="breadcrumb justify-content-center">
                        <li class="breadcrumb-item">
                          <a href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                          Blog
                        </li>
                      </ol>
                    </nav>
                  </div>
                </div>
              </div>
              <!--end col-->
            </div>
            <!--end row-->
          </div>
          <!--end container-->
        </section>
        <!-- end home -->

        <!-- START SHAPE -->
        <div class="position-relative" style="z-index: 1">
          <div class="shape">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 250">
              <path fill="" fill-opacity="1"
                d="M0,192L120,202.7C240,213,480,235,720,234.7C960,235,1200,213,1320,202.7L1440,192L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z">
              </path>
            </svg>
          </div>
        </div>
        <!-- END SHAPE -->

        <!-- START BLOG-PAGE -->
        <section class="section">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-lg-12">
                <div class="mb-4">
                  <h4>Latest & Trending Blog Post</h4>
                </div>
              </div>
              <!--end col-->



              <div class="col-lg-7">
                <div class="post-preview overflow-hidden rounded-3 mb-3 mb-lg-0">
                  <a href="{% url 'single_blog' latest_blog.slug%}"><img src="/media/{{latest_blog.image}}" alt="Blog"
                      class="img-fluid blog-img" /></a>
                </div>
              </div>
              <!--end col-->
              <div class="col-lg-5">
                <!-- Post-->
                <article class="post position-relative">
                  <div class="post ms-lg-4">
                    <p class="text-muted mb-2">
                     <b>
                      {% if latest_blog %} 
                      {% for types in latest_blog.type.all %}
                      {{types}} {% endfor %}</b>- {{latest_blog.created_at|timesince }} ago 
                      {% endif %}
                    </p>
                    <h5 class="mb-3">
                      <a href="{% url 'single_blog' latest_blog.slug%}" class="primary-link">{{ latest_blog.title }}</a>
                    </h5>
                      <p class="text">{{latest_blog.description}}</p>
                      <a class="read-more" href="{% url 'single_blog' latest_blog.slug%}">Read More</a>
                    
                    
                  </div>
                </article>
                <!-- Post end-->
              </div>
              <!--end col-->
            </div>
            <!--end row-->



            <div class="row mt-5">
              <div class="col-lg-12">
                <div>
                  <h4>All Blog Post</h4>
                </div>
              </div>


              {% for blog in blogs %}
              <div class="col-md-4 mt-2">
                <article class="post position-relative mt-4">
                  <div class="post-preview overflow-hidden mb-3 rounded-3">
                    <a href="{% url 'single_blog' blog.slug%}"><img src="/media/{{blog.image}}" alt=""
                        class="img-fluid blog-img" style="width: auto; height: 230px;" /></a>
                  </div>
                  <p class="text-muted mb-2">
                   
                    <b>  {% for type in blog.type.all %} {{type}} {% endfor %} </b> - {{blog.created_at|timesince }} ago
                  </p>
                  <h5 class="mb-3">
                    <a href="{% url 'single_blog' blog.slug %}" class="primary-link">{{blog.title}}</a>
                  </h5>
                  <p class="text">{{blog.description}}</p>
                  <a class="read-more" href="{% url 'single_blog' blog.slug%}">Read More</a>
                </article>
              </div>
              <!--end col-->
              {% endfor %}

          
              <div class="row">
                <div class="col-lg-12 mt-5">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination job-pagination mb-0 justify-content-center">
                          {% if not blogs.has_previous %}
                          <li class="page-item ">
                            <a class="page-link disabled" href="">
                                <i class="mdi mdi-chevron-double-left fs-15"></i>
                            </a>
                        </li>
                        {% endif %}
                          {% if blogs.has_previous %}
                          <li class="page-item ">
                            <a class="page-link" href="?page={{ blogs.previous_page_number }}">
                                <i class="mdi mdi-chevron-double-left fs-15"></i>
                            </a>
                        </li>
                          {% endif %}

                          {% if blogs.has_previous %}
                                <li class="page-item "><a class="page-link" href="?page={{ blogs.previous_page_number }}">{{ blogs.previous_page_number }}</a></li>
                          {% endif %}

                          <span class="current-page">
                            <li class="page-item active"><a class="page-link" href="#">{{ blogs.number }}</a></li>
                          </span>
                           
                          {% if blogs.has_next %}
                          <li class="page-item"><a  class="page-link"  href="?page={{ blogs.next_page_number }}">{{ blogs.next_page_number }}</a></li>
                         {% endif %}

                         {% if blogs.has_next %}
                         <li class="page-item">
                          <a class="page-link" href="?page={{ blogs.next_page_number }}">
                              <i class="mdi mdi-chevron-double-right fs-15"></i>
                          </a>
                          </li>
                        {% endif %}

                        {% if  not blogs.has_next %}
                        <li class="page-item">
                         <a class="page-link disabled " href="">
                             <i class="mdi mdi-chevron-double-right fs-15"></i>
                         </a>
                         </li>
                       {% endif %}
                                <!-- End blog pagination -->
                            
                        </ul>
                    </nav>
                </div><!--end col-->
            </div><!-- end row -->
              
     


            </div>

          </div>
          <!-- end container -->
        </section>
        <!-- END BLOG-PAGE -->
      </div>
      <!-- End Page-content -->

      {% include 'include/footer.html'%}
      {% include 'include/footerjs.html'%}
</body>
</html>

Company/templates/Company/contact.html
{% load static %} {% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Contact | ACT - American College Of Technology </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content=" " />
    <meta name="keywords" content="" />
    <meta content="Themesdesign" name="author" />
    {% include 'include/head.html'%}
  </head>

  <body>
    <!-- Begin page -->
    <div>
      {%include 'include/navbar.html' %}
      <div class="main-content">
        <div class="page-content">
          <!-- Start home -->
          <section class="page-title-box">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="text-center text-white">
                    <h3 class="mb-4">Contact</h3>
                    <div class="page-next">
                      <nav
                        class="d-inline-block"
                        aria-label="breadcrumb text-center"
                      >
                        <ol class="breadcrumb justify-content-center">
                          <li class="breadcrumb-item">
                            <a href="{% url 'index' %}">Home</a>
                          </li>
                          <li class="breadcrumb-item">
                            <a href="javascript:void(0)">Contact</a>
                          </li>
                          <li
                            class="breadcrumb-item active"
                            aria-current="page"
                          >
                            Contact
                          </li>
                        </ol>
                      </nav>
                    </div>
                  </div>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end container-->
          </section>
          <!-- end home -->

          <!-- START SHAPE -->
          <div class="position-relative" style="z-index: 1">
            <div class="shape">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 250">
                <path
                  fill=""
                  fill-opacity="1"
                  d="M0,192L120,202.7C240,213,480,235,720,234.7C960,235,1200,213,1320,202.7L1440,192L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"
                ></path>
              </svg>
            </div>
          </div>
          <!-- END SHAPE -->

          <!-- START CONTACT-PAGE -->
          <section class="section">
            <div class="container">
              <div class="row align-items-center mt-5">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div class="alert alert-success alert-dismissible">
                      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                       {{message}}
                    </div>
                    {% endfor %}
                </ul>
                {% endif %}


                

                <div class="col-lg-6">
                  <div class="section-title mt-4 mt-lg-0">
                    <h3 class="title">Get in touch</h3>
                    <p class="text-muted">
                      Start working with Jobcy that can provide everything you
                      need to generate awareness, drive traffic, connect.
                    </p>
                    <form method="post" class="contact-form mt-4">
                      {% csrf_token %}
                      
                      <span id="error-msg"></span>
                      <div class="row">
                        <div class="col-lg-12">
                          <div class="mb-3">
                            <label for="nameInput" class="form-label"
                              >Name {% for err in form.name.errors %}   <small class="text-danger">{{err}}</small>  {% endfor %} </label
                            >
                            <input
                              type="text"
                              name="name"
                              id="id_name"
                              class="form-control {% if form.name.errors %} is-invalid  {% endif %} "
                              placeholder="Enter your name"
                              required
                            />
                          </div>
                        </div>
                        <!--end col-->
                        <div class="col-md-6">
                          <div class="mb-3">
                            <label for="emailInput" class="form-label"
                              >Email {% for err in form.email.errors %}   <small class="text-danger">{{err}}</small>  {% endfor %}</label
                            >
                            <input
                              type="email"
                              class="form-control  {% if form.email.errors %} is-invalid  {% endif %}"
                              id="id_email"
                              name="email"
                              placeholder="Enter your email"
                              required
                            />
                          </div>
                        </div>
                        <!--end col-->
                        <div class="col-md-6">
                          <div class="mb-3">
                            <label for="subjectInput" class="form-label"
                              >Subject {% for err in form.subject.errors %}   <small class="text-danger">{{err}}</small>  {% endfor %}</label
                            >
                            <input
                              type="text"
                              class="form-control  {% if form.subject.errors %} is-invalid  {% endif %}"
                              id="subjectInput"
                              name="subject"
                              id="id_subject"
                              placeholder="Enter your subject"
                              required
                            />
                          </div>
                        </div>
                        <!--end col-->
                        <div class="col-lg-12">
                          <div class="mb-3">
                            <label for="meassageInput" class="form-label"
                              >Your Message {% for err in form.message.errors %}   <small class="text-danger">{{err}}</small>  {% endfor %}</label
                            >
                            <textarea
                              class="form-control  {% if form.message.errors %} is-invalid  {% endif %}"
                              id="meassageInput"
                              placeholder="Enter your message"
                              name="message"
                              id="id_message"
                              rows="3"
                              required
                            ></textarea>
                          </div>
                        </div>
                        <!--end col-->
                      </div>
                      <!--end row-->
                      <div class="text-end">
                        <button
                          type="submit"
                          id="submit"
                          name="submit"
                          class="btn btn-primary"
                        >
                          Send Message <i class="uil uil-message ms-1"></i>
                        </button>
                      </div>
                    </form>
                    <!--end form-->
                  </div>
                </div>
                <!--end col-->
                <div class="col-lg-5 ms-auto order-first order-lg-last">
                  <div class="text-center">
                    <img
                      src="{% static 'assets/images/contact.png' %}"
                      alt=""
                      class="img-fluid"
                    />
                  </div>
                  <div class="mt-4 pt-3">
                    <div class="d-flex text-muted align-items-center mt-2">
                      <div class="flex-shrink-0 fs-22 text-primary">
                        <i class="uil uil-map-marker"></i>
                      </div>
                      <div class="flex-grow-1 ms-2">
                        <p class="mb-0">{{contact.location}}</p>
                      </div>
                    </div>

                    <div class="d-flex text-muted align-items-center mt-2">
                      <div class="flex-shrink-0 fs-22 text-primary">
                        <i class="uil uil-envelope"></i>
                      </div>
                      <div class="flex-grow-1 ms-2">
                        <p class="mb-0">{{contact.email}}</p>
                      </div>
                    </div>

                    <div class="d-flex text-muted align-items-center mt-2">
                      <div class="flex-shrink-0 fs-22 text-primary">
                        <i class="uil uil-phone-alt"></i>
                      </div>
                      <div class="flex-grow-1 ms-2">
                        <p class="mb-0">{{contact.phone}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end container-->
          </section>
          <!-- START CONTACT-PAGE -->

          <div class="map">
            <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.356360776719!2d38.75922877384892!3d9.031219888956608!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x164b85f0f9a06d85%3A0x4331551f2e0d81cb!2zQUNUIEFtZXJpY2FuIENvbGxlZ2Ugb2YgVGVjaG5vbG9neSB8IDQgS2lsbyB8IOGKoOGKreGJtSDhiqDhiJzhiKrhiqvhipUg4Ym04Yqt4YqW4YiO4YyCIOGKruGIjOGMhSB8IDQg4Yqq4YiO!5e0!3m2!1sen!2set!4v1688731587813!5m2!1sen!2set"height="350"
            style="border: 0; width: 100%"
            allowfullscreen=""
            loading="lazy"
            ></iframe>
            
          </div>
        </div>
        <!-- End Page-content -->
        {% include 'include/footer.html' %}
      </div>
      <!-- end main content-->
    </div>
    <!-- END layout-wrapper -->
    {% include 'include/footerjs.html'%}
  </body>

  <!-- Mirrored from themesdesign.in/jobcy/layout/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 12 Jun 2023 16:56:30 GMT -->
</html>